version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10  # have to specify, this would be handy for some scripts later.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
        - aws cloudformation update-stack --stack-name website-stack --capabilities CAPABILITY_AUTO_EXPAND --template-body file://template.yml
        - aws s3 cp assets/ s3://zach-assets --recursive
        - aws s3 website s3://zach-assets --index-document index.html  # --error-document error.html once we have one
        - aws s3 cp pages/ s3://zach-assets --recursive
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
