AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "The website https://zach-jones.com"
# Parameters:
#   EnvironmentName:
#     Description: Prod or Dev
#     Type: String

Resources:
  # Allow public reads of the assets bucket
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Id: zach-website-bucket-policy
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicReads
            Effect: Allow
            Action:
              - s3:GetObject
            Principal: "*" # anonymous access
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref StaticAssetsBucket
                  - /*
  # this is the assets bucket
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'zach-assets'
